// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIsK0QaYLW0vobfWMqFLVvFhokXZzveFM',
    appId: '1:393055797197:web:ee2b5fe1cd09212fdc8e84',
    messagingSenderId: '393055797197',
    projectId: 'devin-menu-app',
    authDomain: 'devin-menu-app.firebaseapp.com',
    storageBucket: 'devin-menu-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlb8wxUbwLAmKYy3f9XXWJB11iwSvmkWw',
    appId: '1:393055797197:android:e976fc7d767c5f04dc8e84',
    messagingSenderId: '393055797197',
    projectId: 'devin-menu-app',
    storageBucket: 'devin-menu-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6lEVnXa2DeZZl3tH9jY-7Okh41Dq5tp0',
    appId: '1:393055797197:ios:d8875696593403c3dc8e84',
    messagingSenderId: '393055797197',
    projectId: 'devin-menu-app',
    storageBucket: 'devin-menu-app.firebasestorage.app',
    iosBundleId: 'com.example.menu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6lEVnXa2DeZZl3tH9jY-7Okh41Dq5tp0',
    appId: '1:393055797197:ios:d8875696593403c3dc8e84',
    messagingSenderId: '393055797197',
    projectId: 'devin-menu-app',
    storageBucket: 'devin-menu-app.firebasestorage.app',
    iosBundleId: 'com.example.menu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIsK0QaYLW0vobfWMqFLVvFhokXZzveFM',
    appId: '1:393055797197:web:ecfe3a604bdb894ddc8e84',
    messagingSenderId: '393055797197',
    projectId: 'devin-menu-app',
    authDomain: 'devin-menu-app.firebaseapp.com',
    storageBucket: 'devin-menu-app.firebasestorage.app',
  );

}